[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["openzeppelin-contracts-06/math/=lib/forge-std/src/"]

solc_version = "0.6.2"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
